bat: .config/bat/config
gitconfig: .gitconfig
gvimrc: .gvimrc
haskeline: .haskeline
inputrc: .inputrc
nix_conf: .config/nix/nix.conf
nvim: .config/nvim
pylintrc: .pylintrc
sbclrc: .sbclrc
vim: .vim
vimrc: .vimrc
