---
astylerc: .astylerc
ctags: .ctags
dups: bin/dups
ghci: .ghci
gitconfig: .gitconfig
gvimrc: .gvimrc
haskeline: .haskeline
hirc: .hirc
inputrc: .inputrc
irbrc: .irbrc
lein_profile: .lein/profiles.clj
leinrc: .lein/leinrc
nvim: .config/nvim
ocamlinit: .ocamlinit
passive: bin/passive
pylintrc: .pylintrc
sbclrc: .sbclrc
stack_config: .stack/config.yaml
stack_global: .stack/global-project/stack.yaml
stylish_haskell: .stylish-haskell.yaml
tmux_conf: .tmux.conf
todo_cfg: .todo.cfg
vim: .vim
vimrc: .vimrc
weasel: bin/weasel
xinitrc: .xinitrc
xmodmap: .Xmodmap
zshrc: .zshrc
