--- 
astylerc: .astylerc
ghci: .ghci
gitconfig: .gitconfig
gvimrc: .gvimrc
haskeline: .haskeline
hirc: .hirc
inputrc: .inputrc
irbrc: .irbrc
tmux_conf: .tmux.conf
vim: .vim
vimrc: .vimrc
zshrc: .zshrc
