START_YOUR_DAY: bin/START_YOUR_DAY
_tmuxinator: ._tmuxinator
astylerc: .astylerc
bat: .config/bat/config
beamer_template_tex: .pandoc/templates/beamer_template.tex
beamer_dark_template_tex: .pandoc/templates/beamer_dark_template.tex
dups: bin/dups
ghci: .ghci
gitconfig: .gitconfig
gvimrc: .gvimrc
haskeline: .haskeline
inputrc: .inputrc
md2beamer: bin/md2beamer
md2tufte: bin/md2tufte
nvim: .config/nvim
passive: bin/passive
pylintrc: .pylintrc
sbclrc: .sbclrc
scalafmt_conf: .scalafmt.conf
stylish_haskell: .stylish-haskell.yaml
tmux_conf: .tmux.conf
tufte_template_tex: .pandoc/templates/tufte_template.tex
vim: .vim
vimrc: .vimrc
weasel: bin/weasel
zshenv: .zshenv
zshprompt: .zshprompt
zshrc: .zshrc
