bat: .config/bat/config
beamer_dark_template.tex: .pandoc/templates/beamer_dark_template.tex
beamer_template.tex: .pandoc/templates/beamer_template.tex
cabal_config: .cabal/config
dups: bin/dups
ghci: .ghci
gitconfig: .gitconfig
haskeline: .haskeline
helix: .config/helix/config.toml
helix_lang: .config/helix/languages.toml
inputrc: .inputrc
md2beamer: bin/md2beamer
md2tufte: bin/md2tufte
nix_conf: .config/nix/nix.conf
nvim: .config/nvim
ocamlinit: .ocamlinit
passive: bin/passive
qq: bin/qq
radian: .config/radian/profile
rye: .rye/config.toml
sbclrc: .sbclrc
tmux.conf: .tmux.conf
tufte_template.tex: .pandoc/templates/tufte_template.tex
UPUPANDAWAY: bin/UPUPANDAWAY
vim: .vim
vimrc: .vimrc
weasel: bin/weasel
zshrc: .zshrc
