---
astylerc: .astylerc
ghci: .ghci
gitconfig: .gitconfig
gvimrc: .gvimrc
haskeline: .haskeline
hirc: .hirc
inputrc: .inputrc
irbrc: .irbrc
nvim: .config/nvim
ocamlinit: .ocamlinit
lein_profile: .lein/profiles.clj
sbclrc: .sbclrc
stack_config: .stack/config.yaml
todo_cfg: .todo.cfg
tmux_conf: .tmux.conf
vim: .vim
vimrc: .vimrc
xinitrc: .xinitrc
xmodmap: .Xmodmap
zshrc: .zshrc
