astylerc: .astylerc
bat: .config/bat/config
beamer_dark_template.tex: .pandoc/templates/beamer_dark_template.tex
beamer_template.tex: .pandoc/templates/beamer_template.tex
brittany_config.yaml: .config/brittany/config.yaml
dups: bin/dups
ghci: .ghci
gitconfig: .gitconfig
gvimrc: .gvimrc
haskeline: .haskeline
inputrc: .inputrc
latexrun: bin/latexrun
md2beamer: bin/md2beamer
md2tufte: bin/md2tufte
nix_conf: .config/nix.conf
nvim: .config/nvim
passive: bin/passive
pylintrc: .pylintrc
sbclrc: .sbclrc
START_YOUR_DAY: bin/START_YOUR_DAY
stylish-haskell.yaml: .stylish-haskell.yaml
summoner.toml: .summoner.toml
tmux.conf: .tmux.conf
tufte_template.tex: .pandoc/templates/tufte_template.tex
vim: .vim
vimrc: .vimrc
weasel: bin/weasel
zshenv: .zshenv
zshprompt: .zshprompt
zshrc: .zshrc
