START_YOUR_DAY: bin/START_YOUR_DAY
_cargo: site-functions/_cargo
_rustup: site-functions/_rustup
_stack: site-functions/_stack
_tmuxinator: ._tmuxinator
aoc_hsfiles: .stack/templates/aoc.hsfiles
astylerc: .astylerc
beamer_template_tex: .pandoc/templates/beamer_template.tex
beamer_dark_template_tex: .pandoc/templates/beamer_dark_template.tex
ctags: .ctags
dups: bin/dups
eclrc: .eclrc
genos_hsfiles: .stack/templates/genos.hsfiles
ghci: .ghci
gitconfig: .gitconfig
gvimrc: .gvimrc
haskeline: .haskeline
inputrc: .inputrc
md2beamer: bin/md2beamer
md2tufte: bin/md2tufte
nvim: .config/nvim
passive: bin/passive
profiles_clj: .lein/profiles.clj
pylintrc: .pylintrc
qf_hsfiles: .stack/templates/qf.hsfiles
sbclrc: .sbclrc
scalafmt_conf: .scalafmt.conf
scalariform_properties: .scalariform.properties
stack_config: .stack/config.yaml
stack_global: .stack/global-project/stack.yaml
stylish_haskell: .stylish-haskell.yaml
tmux_conf: .tmux.conf
tufte_template_tex: .pandoc/templates/tufte_template.tex
vim: .vim
vimrc: .vimrc
wiki.lua: .pandoc/wiki.lua
weasel: bin/weasel
zshenv: .zshenv
zshprompt: .zshprompt
zshrc: .zshrc
