#!/usr/bin/env python3
"""Convert a markdown file to Beamer & typeset it"""

import argparse
from pathlib import Path
import shlex
import subprocess


def typeset(path: Path) -> None:
    """Convert a markdown file to Beamer & typeset it"""
    output = path.with_suffix(".pdf")
    return subprocess.call(
        shlex.split(
            f"pandoc -t beamer+smart --pdf-engine=xelatex --template=beamer_template.tex --listings {path} -o {output}"
        )
    )


if __name__ == "__main__":
    PARSER = argparse.ArgumentParser(description=__doc__)
    PARSER.add_argument(
        "-i", "--input", help="Markdown file to convert & typeset", required=True
    )
    typeset(Path(PARSER.parse_args().input))
