#!/usr/bin/env python3
"""Convert a markdown file to Beamer & typeset it"""

import argparse
import pathlib
import shlex
import subprocess


def typeset(path: pathlib.Path) -> None:
    """Convert a markdown file to Beamer & typeset it"""
    output = path.with_suffix(".pdf")
    subprocess.call(
        shlex.split(
            f"pandoc -t beamer+smart --pdf-engine=xelatex --template=beamer_template.tex --listings {path} -o {output}"
        )
    )


if __name__ == "__main__":
    PARSER = argparse.ArgumentParser(description=__doc__)
    PARSER.add_argument("-i", "--input", help="Markdown file to convert & typeset", required=True)
    typeset(pathlib.Path(PARSER.parse_args().input))
