#!/usr/bin/env zsh

function ppprint() { print $1 | lolcat }
function ppppprint() { print $1 | figlet -f big | lolcat -a }

function repos() {
  for repo in $HOME/rc/repos/*; do
    if [[ (-d $repo) && (-d $repo/.git) ]] ; then
      ppprint "git pull in ${repo:t}…"
      cd $repo
      git pull --prune
    fi
  done
}

function brews() {
  ppprint "brew update >>= upgrade >>= cask upgrade >>= cleanup…"
  brew update && brew upgrade && brew upgrade --cask && brew cleanup
}

function rusts() {
  ppprint "rustup self update >> rustup update"
  rustup self update
  rustup update
}

function cabals() {
  ppprint "cabal update…"
  cabal update
}

repos; brews; rusts; cabals; ppppprint "DONE!"
