#!/usr/bin/env zsh

function ppprint() { print $1 | lolcat }
function ppppprint() { print $1 | figlet -f big | lolcat -a }

function repos() {
  for repo in $HOME/sw/repos/*; do
    if [[ (-d $repo) && (-d $repo/.git) ]] ; then
      ppprint "git pull in ${repo:t}"
      cd $repo
      git pull --prune
    fi
  done
}

function brews() {
  ppprint "brew update >>= upgrade >>= cask upgrade >>= cleanup"
  cd $HOME
  brew update && brew upgrade --greedy && brew upgrade --cask && brew cleanup
}

function rusts() {
  ppprint "rustup update"
  cd $HOME
  rustup update
}

function haskells() {
  ppprint "ghcup upgrade >> cabal update"
  cd $HOME
  ghcup upgrade
  cabal update
}

repos; brews; rusts; haskells; ppppprint "DONE!"
